#improvments
1. building the neural network using NN module
2. using built-in activation function
3. using built-in loss function
4. using built-in optimizer


In [ ]:
# pytorch--nn--module


In [9]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [10]:
# create a dataset
features = torch.rand(10,5)

In [11]:
#create model
model = Model(features.shape[1])

In [ ]:
#call model for forward pass
#model.forward(features)  # automatically called 
model(features)

tensor([[0.3034],
        [0.4183],
        [0.3327],
        [0.4252],
        [0.3394],
        [0.4751],
        [0.3836],
        [0.3867],
        [0.3766],
        [0.4049]], grad_fn=<SigmoidBackward0>)

In [18]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3754, -0.3998, -0.3167,  0.3341, -0.4195]], requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([-0.3238], requires_grad=True)

In [ ]:
# for visualization #!pip install torchinfo
from torchinfo import summary

In [21]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# more complex NN

In [1]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [2]:
#create model class # using sequential containers
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out