In [2]:
import torch
print(torch.__version__)

2.13.0+cu130


In [3]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("CUDA is not available. You will be using CPU.")

CUDA is available. You can use GPU acceleration.
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


Creating a tensor

In [4]:
#using empty
x = torch.empty(2, 3)

In [5]:
x

tensor([[1.3085e+08, 3.0941e-41, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [6]:
# check type
type(x)

torch.Tensor

In [7]:
# using zeros
y = torch.zeros(2, 3)

In [8]:
y # used for initialization of weights/baises in neural networks

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
z = torch.ones(2, 3)

In [10]:
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using randn
torch.randn(2, 3)

tensor([[-0.3628,  1.6543, -0.1874],
        [ 1.7611, -0.6991,  0.4519]])

In [12]:
(torch.randn(2, 3))

tensor([[ 1.5992, -0.7541,  2.0206],
        [-0.8170, -0.3760,  0.2241]])

In [13]:
#use of seed
torch.randn(2, 3)

tensor([[ 0.4556,  0.8917,  0.5947],
        [ 0.2223, -1.2893, -0.7084]])

In [14]:
# manual_seed  # used to set the seed for generating random numbers. It ensures that the results are reproducible.(increases the reproducibility of experiments by ensuring that the same random numbers are generated each time the code is run.)
torch.manual_seed(100)
torch.randn(2, 3)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [15]:
torch.manual_seed(100)
torch.randn(2, 3)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134]])

In [16]:
# using tensor  (creates a tensor from a Python list or tuple. It allows you to convert existing data into a PyTorch tensor for further computations.)
torch.tensor([[1, 2,3], [4, 5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other way to create tensor

#arrange  (creates a tensor with evenly spaced values within a specified range. It allows you to generate sequences of numbers for various purposes, such as creating input data or defining ranges for computations.)
print("using arrange -->", torch.arange(0, 10, 2))  # start, end, step

#using linespace  (creates a tensor with evenly spaced values over a specified interval. It is often used for generating points in a continuous range, such as for plotting or sampling.)
print("using linespace -->", torch.linspace(0, 1, steps=5))

#using eye  (creates a 2D tensor with ones on the diagonal and zeros elsewhere. It is commonly used to create identity matrices, which are useful in linear algebra and various mathematical operations.)
print("using eye -->", torch.eye(3))

#using full  (creates a tensor filled with a specified value. It allows you to initialize tensors with a constant value, which can be useful for certain computations or as a starting point for optimization.)
print("using full -->", torch.full((2, 3), 7))  # (shape, fill_value)


using arrange --> tensor([0, 2, 4, 6, 8])
using linespace --> tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
using eye --> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full --> tensor([[7, 7, 7],
        [7, 7, 7]])


Tensor shape

In [18]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape  # returns the shape of the tensor as a tuple, indicating the number of dimensions and the size of each dimension.

torch.Size([2, 3])

In [20]:
torch.empty_like(x)  # creates a new tensor with the same shape and data type as the input tensor x, but without initializing its values. The contents of the new tensor are uninitialized and may contain arbitrary values.

tensor([[94834211616692,              0,             56],
        [   68719476752,              5,              0]])

In [21]:
torch.zeros_like(x)  # creates a new tensor with the same shape and data type as the input tensor x, but filled with zeros. It is useful for initializing tensors with a specific shape while ensuring that all elements are set to zero.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)  # creates a new tensor with the same shape and data type as the input tensor x, but filled with ones. It is useful for initializing tensors with a specific shape while ensuring that all elements are set to one.

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.randn_like(x)  # creates a new tensor with the same shape and data type as the input tensor x, but filled with random values drawn from a standard normal distribution (mean=0, std=1). It is useful for initializing tensors with random values while maintaining the same shape as the original tensor.

NotImplementedError: "normal_kernel_cpu" not implemented for 'Long'

In [24]:
torch.randn_like(x, dtype=torch.float32)  # creates a new tensor with the same shape and data type as the input tensor x, but filled with random values drawn from a standard normal distribution (mean=0, std=1). It is useful for initializing tensors with random values while maintaining the same shape as the original tensor.

tensor([[-0.3172, -0.8660,  1.7482],
        [-0.2759, -0.9755,  0.4790]])

Tensor Data types

In [25]:
# find data type of tensor
x.dtype  # returns the data type of the tensor x, indicating the type of elements stored

torch.int64

In [26]:
# assigning new data type to tensor
x = x.to(torch.float32)  # converts the tensor x to the specified data type
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=torch.int32)  # creates a tensor with the specified data type (in this case, int32). It allows you to explicitly define the data type of the tensor elements during creation.

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [28]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
# using to()  (converts the tensor to a specified data type or device. It allows you to change the data type of the tensor elements or move the tensor to a different device, such as from CPU to GPU, for efficient computations.)
x = x.to(torch.float32)  # converts the tensor x to the specified data type
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [30]:
dtype_info = {
    torch.float16: "16-bit floating point",
    torch.float32: "32-bit floating point, common for neural network computations",
    torch.float64: "64-bit floating point, for high-precision calculations",
    torch.bfloat16: "16-bit brain floating point, used for faster training with mixed precision",
    torch.complex64: "64-bit complex number (two 32-bit floats)",
    torch.complex128: "128-bit complex number (two 64-bit floats)",
    torch.uint8: "8-bit unsigned integer",
    torch.int8: "8-bit signed integer",
    torch.int16: "16-bit signed integer",
    torch.int32: "32-bit signed integer",
    torch.int64: "64-bit signed integer",
    torch.bool: "Boolean value (True/False)",
    torch.qint8: "Quantized 8-bit signed integer",
    torch.quint8: "Quantized 8-bit unsigned integer",
    torch.qint32: "Quantized 32-bit signed integer",
}

for dtype, desc in dtype_info.items():
    print(f"{dtype}: {desc}")

torch.float16: 16-bit floating point
torch.float32: 32-bit floating point, common for neural network computations
torch.float64: 64-bit floating point, for high-precision calculations
torch.bfloat16: 16-bit brain floating point, used for faster training with mixed precision
torch.complex64: 64-bit complex number (two 32-bit floats)
torch.complex128: 128-bit complex number (two 64-bit floats)
torch.uint8: 8-bit unsigned integer
torch.int8: 8-bit signed integer
torch.int16: 16-bit signed integer
torch.int32: 32-bit signed integer
torch.int64: 64-bit signed integer
torch.bool: Boolean value (True/False)
torch.qint8: Quantized 8-bit signed integer
torch.quint8: Quantized 8-bit unsigned integer
torch.qint32: Quantized 32-bit signed integer


#Mathematical operations 

1. Scalar operation

In [31]:
x =torch.rand(2,2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [32]:
#addtion
x + 2

tensor([[2.4440, 2.9478],
        [2.7445, 2.4892]])

In [33]:
#subtraction
x - 2

tensor([[-1.5560, -1.0522],
        [-1.2555, -1.5108]])

In [34]:
#multiplication
x * 2

tensor([[0.8880, 1.8957],
        [1.4890, 0.9784]])

In [35]:
# division
x / 2

tensor([[0.2220, 0.4739],
        [0.3722, 0.2446]])

In [36]:
# int division
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [37]:
(x *100) // 2

tensor([[22., 47.],
        [37., 24.]])

In [38]:
#modulus
x % 2
((x *100) // 2) % 2


tensor([[0., 1.],
        [1., 0.]])

In [39]:
# Power
x ** 2

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

2. Element-wise operation

In [40]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [41]:
# add
a + b

tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [42]:
#sub
a - b

tensor([[ 0.2257,  0.4794, -0.4258],
        [-0.4592,  0.6280, -0.4667]])

In [43]:
#multiply
a * b

tensor([[0.0041, 0.1547, 0.5032],
        [0.1746, 0.1288, 0.3770]])

In [44]:
# division
a / b

tensor([[14.3533,  3.1705,  0.5534],
        [ 0.3499,  4.8557,  0.4757]])

In [45]:
# power
a ** b

tensor([[0.9763, 0.9243, 0.5436],
        [0.3726, 0.9625, 0.4654]])

In [46]:
# mod
a % b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [47]:
c = torch.tensor([1,-1,3,-4])

In [48]:
#absolute value
torch.abs(c)

tensor([1, 1, 3, 4])

In [49]:
# negative
torch.neg(c)

tensor([-1,  1, -3,  4])

In [50]:
d = torch.tensor([1.9, -2.5, 3.7, -4.1])

In [51]:
# round
torch.round(d)

tensor([ 2., -2.,  4., -4.])

In [52]:
#ceil
torch.ceil(d)

tensor([ 2., -2.,  4., -4.])

In [53]:
#floor
torch.floor(d)

tensor([ 1., -3.,  3., -5.])

In [54]:
#clamps the input tensor to the range [min, max] and returns a new tensor with the clamped values. It is useful for restricting values within a specified range.
torch.clamp(d, min=-3, max=3)

tensor([ 1.9000, -2.5000,  3.0000, -3.0000])

# 3. reduction Operation

In [55]:
e = torch.randint(size=(2, 3), low=0, high=10)  
# creates a tensor of shape (2, 3) with random integers between 0 (inclusive) and 10 (exclusive). It is useful for generating random integer data for various purposes, such as testing or simulations. 
e

tensor([[5, 7, 5],
        [9, 9, 7]])

In [56]:
#sum
torch.sum(e)  # computes the sum of all elements in the tensor e. It is useful for aggregating values and obtaining a single scalar result from a tensor.

tensor(42)

In [57]:
#sum along columns (dim=0) or rows (dim=1)
torch.sum(e, dim=0)  # computes the sum of elements along the specified dimension
torch.sum(e, dim=1)  # computes the sum of elements along the specified dimension

tensor([17, 25])

In [58]:
# mean
torch.mean(e.float())  # computes the mean (average) of all elements in the tensor

tensor(7.)

In [59]:
# mean along columns (dim=0) or rows (dim=1)
torch.mean(e.float(), dim=0)  # computes the mean of elements along the specified dimension
torch.mean(e.float(), dim=1)  # computes the mean of elements along the specified dimension

tensor([5.6667, 8.3333])

In [60]:
# median
torch.median(e)  # computes the median of all elements in the tensor e. It is useful for finding the middle value in a sorted list of numbers.

tensor(7)

In [61]:
# max and min
torch.max(e)  # computes the maximum value among all elements in the tensor e. It is useful for finding the largest value in a tensor, which can be important for various applications such as normalization, thresholding, or identifying the most significant feature in a dataset.
torch.min(e)

tensor(5)

In [62]:
# product
torch.prod(e)  # computes the product of all elements in the tensor e. It is

tensor(99225)

In [63]:
# standard deviation
torch.std(e.float())  # computes the standard deviation of all elements in the tensor e.

tensor(1.7889)

In [64]:
#variance
torch.var(e.float())  # computes the variance of all elements in the tensor e. It

tensor(3.2000)

In [65]:
# argmax
torch.argmax(e)  # returns the index of the maximum value in the tensore. It is useful for identifying the position of the largest element in a tensor, which can be important for tasks such as classification or optimization.

tensor(3)

In [66]:
# argmin
torch.argmin(e)  # returns the index of the minimum value in the tensore. It is useful for identifying the position of the smallest element in a tensor,           

tensor(0)

# 4.matrix Operations

In [67]:
f = torch.randint(size=(2, 3), low=0, high=10)  # creates a tensor of shape (2, 3) with random integers between 0 (inclusive) and 10 (exclusive). It is useful for generating random integer data for various purposes, such as testing or simulations.
g = torch.randint(size=(3, 2), low=0, high=10)  # creates a tensor of shape (3, 2) with random integers between 0 (inclusive) and 10 (exclusive). It is useful for generating random integer data for various purposes, such as testing or simulations.

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [68]:
# matrix multiplication
torch.matmul(f, g)  # performs matrix multiplication between tensors f and g. It is useful for linear algebra operations, such as transforming data or computing dot products in neural networks.   

tensor([[137, 117],
        [139, 130]])

In [69]:
# dot product
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])
dot_product = torch.dot(vector1, vector2)  # computes the dot product of two 1D tensors (vectors). It is useful for measuring the similarity or projection of one vector onto another, which has applications in various fields such as machine learning, physics, and computer graphics.
dot_product 

tensor(32)

In [70]:
f

tensor([[5, 9, 8],
        [9, 7, 9]])

In [71]:
# transpose
torch.transpose(f, 0, 1)  # returns a new tensor with the dimensions of the input tensor f transposed. It is useful for rearranging the axes of a tensor, such as converting between row-major and column-major storage formats.

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [72]:
#determinant
torch.det(torch.tensor([[1, 2], [3, 4]], dtype=torch.float32))  # computes the determinant of a square matrix represented by a 2D tensor. It is useful for determining properties of the matrix, such as invertibility, and has applications in linear algebra

tensor(-2.)

In [73]:
# inverse
torch.inverse(torch.tensor([[1, 2], [3, 4]], dtype=torch.float32))  # computes the inverse of a square matrix represented by a 2D tensor. It is useful for solving systems of linear equations, finding the inverse transformation, and has applications in various fields

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

#5. Comparison operation

In [74]:
i = torch.randint(size=(2, 3), low=0, high=10)  # creates a tensor of shape (2, 3) with random integers between 0 (inclusive) and 10 (exclusive). It is useful for generating random integer data for various purposes, such as testing or simulations.
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8, 8],
        [3, 3, 5]])


In [75]:
# greater than
torch.gt(i, j)  # performs element-wise comparison between tensors i and j
#or
i>j

tensor([[ True, False, False],
        [ True, False, False]])

In [76]:
# less than
torch.lt(i, j)  # performs element-wise comparison between tensors i and j
#or

i<j

tensor([[False,  True,  True],
        [False,  True,  True]])

In [77]:
# equal to
torch.eq(i, j)  # performs element-wise comparison between tensors i and j, returning a boolean tensor indicating where the elements are equal

tensor([[False, False, False],
        [False, False, False]])

In [78]:
# not equal to
torch.ne(i, j)  # performs element-wise comparison between tensors i and j

tensor([[True, True, True],
        [True, True, True]])

In [79]:
i !=j

tensor([[True, True, True],
        [True, True, True]])

In [80]:
# greater than equal to
torch.ge(i, j)  # performs element-wise comparison between tensors i and j

tensor([[ True, False, False],
        [ True, False, False]])

In [81]:
# less than equal to
torch.le(i, j)  # performs element-wise comparison between tensors i and j

tensor([[False,  True,  True],
        [False,  True,  True]])

# 6. Special functions

In [82]:
k = torch.randint(size=(2, 3), low=0, high=10,dtype=torch.float32)  # creates a tensor of shape (2, 3) with random integers between 0 (inclusive) and 10 (exclusive). It is useful for generating random integer data for various purposes, such as testing or simulations.
k

tensor([[0., 6., 4.],
        [0., 8., 4.]])

In [83]:
#log
torch.log(k)

tensor([[  -inf, 1.7918, 1.3863],
        [  -inf, 2.0794, 1.3863]])

In [84]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 4.0343e+02, 5.4598e+01],
        [1.0000e+00, 2.9810e+03, 5.4598e+01]])

In [85]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 2.4495, 2.0000],
        [0.0000, 2.8284, 2.0000]])

In [86]:
#sigmoid
torch.sigmoid(k)  # applies the sigmoid function element-wise to the tensor k, returning

tensor([[0.5000, 0.9975, 0.9820],
        [0.5000, 0.9997, 0.9820]])

In [87]:
# softmax
torch.softmax(k, dim=1)  # applies the softmax function along the specified dimension

tensor([[2.1785e-03, 8.7888e-01, 1.1894e-01],
        [3.2932e-04, 9.8169e-01, 1.7980e-02]])

In [88]:
#relu
torch.relu(k)  # applies the rectified linear unit (ReLU) function element-wise to the tensor k, returning a new tensor with all negative values replaced by zero. It is commonly used as an activation function in neural networks to introduce non-linearity and help the model learn complex patterns

tensor([[0., 6., 4.],
        [0., 8., 4.]])

# INplace Operation



In [89]:
m = torch.randn(2,3)
n = torch.randn(2,3)

print(m)
print(n)

tensor([[ 0.6139, -0.9933, -1.1286],
        [-0.8027, -1.5035, -1.2893]])
tensor([[ 0.7983,  0.8991,  0.6286],
        [ 0.8412, -1.5565, -0.1410]])


In [90]:
 m + n #genrating a new tensor 

tensor([[ 1.4122, -0.0942, -0.5000],
        [ 0.0385, -3.0600, -1.4303]])

In [91]:
# but if u want that addtion happens between the m and n ,but the result is stored in m, then u can do this
m.add_(n)  # performs in-place addition of tensor n to tensor m, modifying the values of m directly. It is useful for updating the values of a tensor without creating a new tensor, which can save memory and improve performance in certain scenarios.

tensor([[ 1.4122, -0.0942, -0.5000],
        [ 0.0385, -3.0600, -1.4303]])

In [92]:
m

tensor([[ 1.4122, -0.0942, -0.5000],
        [ 0.0385, -3.0600, -1.4303]])

In [93]:
n

tensor([[ 0.7983,  0.8991,  0.6286],
        [ 0.8412, -1.5565, -0.1410]])

In [94]:
torch.relu(m)  # applies the rectified linear unit (ReLU) function element-wise to the tensor m, returning a new tensor with all negative values replaced by zero. It is commonly used as an activation function in neural networks to introduce non-linearity and help the model learn complex patterns.

tensor([[1.4122, 0.0000, 0.0000],
        [0.0385, 0.0000, 0.0000]])

In [95]:
m.relu_()  # applies the rectified linear unit (ReLU) function element-wise to the tensor m in-place, modifying the values of m directly. It is useful for introducing non-linearity in neural networks while saving memory by avoiding the creation of a new tensor.  

tensor([[1.4122, 0.0000, 0.0000],
        [0.0385, 0.0000, 0.0000]])

In [96]:
m

tensor([[1.4122, 0.0000, 0.0000],
        [0.0385, 0.0000, 0.0000]])

# coping a tensor

In [97]:
a = torch.randn(2, 3)
a

tensor([[ 0.2437, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [98]:
b = a

In [99]:
b

tensor([[ 0.2437, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [100]:
a[0][0] = 0

In [101]:
a

tensor([[ 0.0000, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [102]:
b

tensor([[ 0.0000, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [103]:
id(a)  # returns the unique identifier (memory address) of the tensor a. It is useful for checking if two variables refer to the same tensor in memory.

140193914607312

In [104]:
id(b)  # returns the unique identifier (memory address) of the tensor b. It is useful for checking if two variables refer to the same tensor in memory.

140193914607312

In [105]:
b = a.clone()  # creates a new tensor that is a copy of the tensor a, with its own memory allocation. It is useful for creating independent copies of tensors to avoid unintended modifications when working with shared references.    

In [106]:
a

tensor([[ 0.0000, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [107]:
b

tensor([[ 0.0000, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [108]:
a[0, 0] = 100  # modifies the first element of the first row of tensor a to be 100. This demonstrates that tensors in PyTorch are mutable, and changes to one tensor can affect another tensor if they share the same underlying data.

In [109]:
a

tensor([[100.0000,  -0.5800,  -0.1542],
        [  1.1046,  -1.1368,  -1.0865]])

In [110]:
b

tensor([[ 0.0000, -0.5800, -0.1542],
        [ 1.1046, -1.1368, -1.0865]])

In [111]:
id(a)  # returns the unique identifier (memory address) of the tensor a. It is useful for checking if two variables refer to the same tensor in memory.

140193914607312

In [112]:
id(b)  # returns the unique identifier (memory address) of the tensor b. It is useful for checking if two variables refer to the same tensor in memory.

140193914765392

# Tensor Operations on GPU

In [113]:
torch.cuda.is_available()  # checks if CUDA (GPU acceleration) is available on the system. It returns True if a compatible GPU is detected and can be used for computations, otherwise it returns False. This is useful for determining whether to run computations on the GPU or CPU.

True

In [114]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")  # creates a device object that represents the available computing device (GPU or CPU). It is useful for specifying where tensors and models should be allocated for efficient computations.

In [115]:
# creating new tensors on GPU
a = torch.randn(2, 3).to(device)
a

tensor([[-0.4461, -1.7313,  0.3699],
        [-0.3564, -0.3377, -0.1462]], device='cuda:0')

In [116]:
# moving existing tensors of cpu to GPU
b = a.to(device)

In [117]:
b

tensor([[-0.4461, -1.7313,  0.3699],
        [-0.3564, -0.3377, -0.1462]], device='cuda:0')

In [118]:
b + 5

tensor([[4.5539, 3.2687, 5.3699],
        [4.6436, 4.6623, 4.8538]], device='cuda:0')

In [120]:
# code for comparing the performance of CPU and GPU for tensor operations in PyTorch. It measures the time taken to perform a large number of tensor additions on both CPU and GPU, allowing you to see the speedup achieved by using GPU acceleration for computations.
import time
import torch

#Define the size of the matrix
matrix_size = 10000 #large size to see the difference in performance between CPU and GPU

#create random matrices on CPU
matrix_cpu_1 = torch.randn(matrix_size, matrix_size)
matrix_cpu_2 = torch.randn(matrix_size, matrix_size)

# Measure time taken for matrix addition on CPU
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix_cpu_1, matrix_cpu_2) #matrix multiplication on cpu
cpu_time = time.time() - start_time_cpu

print(f"Time taken for matrix multiplication on CPU: {cpu_time:.6f} seconds")

 #move matrices to GPU if available
matrix_gpu_1 = matrix_cpu_1.to(device)
matrix_gpu_2 = matrix_cpu_2.to(device)

# Measure time taken for matrix addition on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(matrix_gpu_1, matrix_gpu_2) #matrix multiplication on gpu
torch.cuda.synchronize()  # Wait for all GPU operations to finish before measuring time
gpu_time = time.time() - start_time_gpu

print(f"Time taken for matrix multiplication on GPU: {gpu_time:.6f} seconds")

#compare the results
print("\nspeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time taken for matrix multiplication on CPU: 14.300880 seconds
Time taken for matrix multiplication on GPU: 0.643914 seconds

speedup (CPU time / GPU time): 22.20929423142716


# Reshaping the tensors

In [121]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
# reshape
a.reshape(2,2,2,2)  # reshapes the tensor a into a new shape (2, 2, 2, 2). It is useful for changing the dimensions of a tensor to fit the requirements of specific operations or models.

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [123]:
# flatten
a.flatten()  # flattens the tensor a into a 1D tensor. It is useful for converting multi-dimensional tensors into a single dimension, which can be helpful for feeding data into

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [131]:
b=torch.rand(2,3,4)
b


tensor([[[0.5416, 0.4059, 0.3982, 0.4293],
         [0.7526, 0.8673, 0.1561, 0.3627],
         [0.4080, 0.0238, 0.9556, 0.0546]],

        [[0.9876, 0.7779, 0.1610, 0.0409],
         [0.2777, 0.5977, 0.7007, 0.1637],
         [0.3872, 0.8402, 0.1092, 0.4046]]])

In [132]:
b.shape

torch.Size([2, 3, 4])

In [ ]:
#permute
b.permute(2, 0, 1)  # rearranges the dimensions of the tensor b according to the specified order. It is useful for changing the order of dimensions in a tensor, which can be necessary for certain operations or to match the expected input format of specific models or

tensor([[[0.4301, 0.7109, 0.0610],
         [0.1323, 0.7165, 0.7421]],

        [[0.4385, 0.0148, 0.7108],
         [0.2127, 0.1591, 0.5736]],

        [[0.7375, 0.7262, 0.5127],
         [0.9785, 0.2860, 0.1984]],

        [[0.5494, 0.4660, 0.8211],
         [0.3362, 0.1827, 0.7901]]])

In [129]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [133]:
#unsqueeze
c = torch.rand(226,226,3)
c


tensor([[[0.3539, 0.5803, 0.0621],
         [0.3397, 0.2102, 0.9003],
         [0.9300, 0.2240, 0.2525],
         ...,
         [0.9487, 0.2099, 0.8476],
         [0.6727, 0.6128, 0.7182],
         [0.2612, 0.3562, 0.6196]],

        [[0.2052, 0.9444, 0.0385],
         [0.4012, 0.8760, 0.2689],
         [0.7486, 0.9468, 0.9516],
         ...,
         [0.8134, 0.4916, 0.9136],
         [0.7976, 0.4889, 0.7488],
         [0.2050, 0.3059, 0.4419]],

        [[0.0613, 0.6029, 0.8731],
         [0.7505, 0.9560, 0.8368],
         [0.6747, 0.4105, 0.3080],
         ...,
         [0.4762, 0.7536, 0.9295],
         [0.4619, 0.8882, 0.6133],
         [0.1631, 0.5767, 0.8064]],

        ...,

        [[0.7938, 0.1875, 0.8323],
         [0.1491, 0.3159, 0.9957],
         [0.7411, 0.6050, 0.6922],
         ...,
         [0.8114, 0.4960, 0.4968],
         [0.6640, 0.1073, 0.5447],
         [0.3223, 0.4036, 0.8356]],

        [[0.2719, 0.2064, 0.2433],
         [0.4904, 0.9977, 0.3866],
         [0.

In [134]:
# unsqueeze adds a dimension of size 1 at the specified position in the tensor. It is useful for adjusting the shape of a tensor to match the expected input format of certain operations or models, especially when working with batch dimensions or channels in deep learning.        
c.unsqueeze(0)  # adds a dimension of size 1 at the beginning of the tensor c.

tensor([[[[0.3539, 0.5803, 0.0621],
          [0.3397, 0.2102, 0.9003],
          [0.9300, 0.2240, 0.2525],
          ...,
          [0.9487, 0.2099, 0.8476],
          [0.6727, 0.6128, 0.7182],
          [0.2612, 0.3562, 0.6196]],

         [[0.2052, 0.9444, 0.0385],
          [0.4012, 0.8760, 0.2689],
          [0.7486, 0.9468, 0.9516],
          ...,
          [0.8134, 0.4916, 0.9136],
          [0.7976, 0.4889, 0.7488],
          [0.2050, 0.3059, 0.4419]],

         [[0.0613, 0.6029, 0.8731],
          [0.7505, 0.9560, 0.8368],
          [0.6747, 0.4105, 0.3080],
          ...,
          [0.4762, 0.7536, 0.9295],
          [0.4619, 0.8882, 0.6133],
          [0.1631, 0.5767, 0.8064]],

         ...,

         [[0.7938, 0.1875, 0.8323],
          [0.1491, 0.3159, 0.9957],
          [0.7411, 0.6050, 0.6922],
          ...,
          [0.8114, 0.4960, 0.4968],
          [0.6640, 0.1073, 0.5447],
          [0.3223, 0.4036, 0.8356]],

         [[0.2719, 0.2064, 0.2433],
          [0.4904

In [ ]:
c.unsqueeze(0).shape  # mostly used in image genrations

torch.Size([1, 226, 226, 3])

In [136]:
# squeeze removes dimensions of size 1 from the tensor. It is useful for simplifying the shape of a tensor by eliminating unnecessary dimensions, which can help in aligning tensor shapes for various operations or models.    
d = torch.rand(1, 226, 226, 3)
d.squeeze(0)

tensor([[[0.4375, 0.8759, 0.6815],
         [0.7504, 0.5928, 0.2658],
         [0.8542, 0.1179, 0.4115],
         ...,
         [0.9594, 0.3658, 0.1495],
         [0.1967, 0.8550, 0.2603],
         [0.5880, 0.6102, 0.2706]],

        [[0.0339, 0.2805, 0.2541],
         [0.4372, 0.4111, 0.5183],
         [0.2719, 0.3131, 0.6709],
         ...,
         [0.3338, 0.7131, 0.1524],
         [0.7552, 0.8225, 0.7695],
         [0.0467, 0.1858, 0.3493]],

        [[0.1957, 0.5769, 0.2592],
         [0.9252, 0.5834, 0.8656],
         [0.7925, 0.0399, 0.4190],
         ...,
         [0.9701, 0.0789, 0.5081],
         [0.4410, 0.3863, 0.5821],
         [0.6840, 0.9588, 0.8226]],

        ...,

        [[0.4854, 0.2517, 0.1772],
         [0.4497, 0.1108, 0.4433],
         [0.2199, 0.0631, 0.7333],
         ...,
         [0.2968, 0.8883, 0.9424],
         [0.4897, 0.0667, 0.7157],
         [0.3561, 0.9419, 0.4966]],

        [[0.5505, 0.3678, 0.8555],
         [0.7019, 0.7620, 0.3095],
         [0.

In [137]:
d.squeeze(0).shape  # removes the dimension of size 1 at the specified position in the tensor d, returning a new tensor with the reduced shape. It is useful for simplifying the shape of a tensor by eliminating unnecessary dimensions, which can help in aligning tensor shapes for various operations or models.

torch.Size([226, 226, 3])

#moving tensors between numpy and pytorch

In [138]:
import numpy as np

In [139]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Convert PyTorch tensor to NumPy array
numpy_array = a.numpy()
print("NumPy Array:\n", numpy_array)

NumPy Array:
 [[1 2 3]
 [4 5 6]]


In [140]:
b = a.numpy()

In [141]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
type(b)  # returns the type of the variable b, which is a NumPy ndarray. It is useful for confirming the data structure and understanding how to work with the variable in Python.

numpy.ndarray

In [144]:
c = np.array([[1, 2, 3]])
c

array([[1, 2, 3]])

In [145]:
torch.from_numpy(c)  # creates a PyTorch tensor from a NumPy array c. It allows you to convert existing NumPy data into a PyTorch tensor for further computations and operations within the PyTorch framework.

tensor([[1, 2, 3]])